### ISSUE TITLE
Error: Property 'containerDefinitions' could not be serialized: Error: spawn docker ENOENT

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-cloud#206]
Trying to `pulumi preview` the `lm-cts` stack leads to the following on my machine:

```
info: Successfully built 2b2a08640b00
info: Successfully tagged pulumi-luke-container-323e3584:latest
info: Skipping image publish during preview: pulumi-luke-container-323e3584
info:     build complete: pulumi-luke-container-323e3584 (sha256:2b2a08640b00e3c4232337bf8bd9eb3c5bc3750a8a8df1ff3805a7506021e84b)
info:     already built: pulumi-luke-container-323e3584 (sha256:2b2a08640b00e3c4232337bf8bd9eb3c5bc3750a8a8df1ff3805a7506021e84b)
info:     already built: pulumi-luke-container-323e3584 (sha256:2b2a08640b00e3c4232337bf8bd9eb3c5bc3750a8a8df1ff3805a7506021e84b)
info:     already built: pulumi-luke-container-323e3584 (sha256:2b2a08640b00e3c4232337bf8bd9eb3c5bc3750a8a8df1ff3805a7506021e84b)
info:     already built: pulumi-luke-container-323e3584 (sha256:2b2a08640b00e3c4232337bf8bd9eb3c5bc3750a8a8df1ff3805a7506021e84b)
info:     already built: pulumi-luke-container-323e3584 (sha256:2b2a08640b00e3c4232337bf8bd9eb3c5bc3750a8a8df1ff3805a7506021e84b)
info:     already built: pulumi-luke-container-323e3584 (sha256:2b2a08640b00e3c4232337bf8bd9eb3c5bc3750a8a8df1ff3805a7506021e84b)
info:     already built: pulumi-luke-container-323e3584 (sha256:2b2a08640b00e3c4232337bf8bd9eb3c5bc3750a8a8df1ff3805a7506021e84b)
info:     already built: pulumi-luke-container-323e3584 (sha256:2b2a08640b00e3c4232337bf8bd9eb3c5bc3750a8a8df1ff3805a7506021e84b)
info:     already built: pulumi-luke-container-323e3584 (sha256:2b2a08640b00e3c4232337bf8bd9eb3c5bc3750a8a8df1ff3805a7506021e84b)
info:     already built: pulumi-luke-container-323e3584 (sha256:2b2a08640b00e3c4232337bf8bd9eb3c5bc3750a8a8df1ff3805a7506021e84b)
info:     already built: pulumi-luke-container-323e3584 (sha256:2b2a08640b00e3c4232337bf8bd9eb3c5bc3750a8a8df1ff3805a7506021e84b)
info:     already built: pulumi-luke-container-323e3584 (sha256:2b2a08640b00e3c4232337bf8bd9eb3c5bc3750a8a8df1ff3805a7506021e84b)
info:     already built: pulumi-luke-container-323e3584 (sha256:2b2a08640b00e3c4232337bf8bd9eb3c5bc3750a8a8df1ff3805a7506021e84b)
error: Error: Resouce 'lm-cts-luke-lm-cert-issuer' [aws:ecs/taskDefinition:TaskDefinition] could not be created
    at Object.registerResource (/Users/luke/go/src/github.com/pulumi/pulumi/sdk/nodejs/runtime/resource.ts:76:32)
    at TaskDefinition.register (/Users/luke/go/src/github.com/pulumi/pulumi/sdk/nodejs/resource.ts:110:17)
    at TaskDefinition.CustomResource (/Users/luke/go/src/github.com/pulumi/pulumi/sdk/nodejs/resource.ts:140:14)
    at TaskDefinition (/Users/luke/go/src/github.com/pulumi/pulumi-aws/pack/ecs/taskDefinition.ts:63:9)
    at createTaskDefinition (/Users/luke/go/src/github.com/pulumi/pulumi-cloud/aws/service.ts:684:28)
    at Service (/Users/luke/go/src/github.com/pulumi/pulumi-cloud/aws/service.ts:777:40)
    at Function.runInParentScope (/Users/luke/go/src/github.com/pulumi/pulumi/sdk/nodejs/resource.ts:33:20)
    at Service.ComponentResource (/Users/luke/go/src/github.com/pulumi/pulumi/sdk/nodejs/resource.ts:164:68)
    at Service (/Users/luke/go/src/github.com/pulumi/pulumi-cloud/aws/service.ts:743:9)
    at Object.<anonymous> (/Users/luke/go/src/github.com/pulumi/learningmachine-cts/tool/pulumi/issuer.ts:8:15)
error: Failed to create resource 'lm-cts-luke-lm-cert-issuer' [aws:ecs/taskDefinition:TaskDefinition]: Error: Property 'containerDefinitions' could not be serialized: Error: spawn docker ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
    at serializeProperty.then (/Users/luke/go/src/github.com/pulumi/pulumi/sdk/nodejs/runtime/rpc.ts:69:31)
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
error: One or more errors occurred during this preview
```

**Comment by gerrywastaken** [comment]
So when searching `Error: spawn pulumi ENOENT` in Google this is one of the top results. So I thought I'd post some help here as I and others will no doubt be back one day.

It turns out that you will get an error about Pulumi not existing, even if the actual error is that you tried to use a working directory that doesn't exist.

e.g.
```ts
 const args: LocalProgramArgs = {
    stackName: "cert_example_dev",
    workDir: upath.joinSafe(__dirname, "..", "cert_manger_example"),
  };
```

Notice the issue? `manager` not `manger` :man_facepalming: 

That error message really sent me down the wrong path. :smirk:  I eventually figured it out by adding copious logging here:
 https://github.com/pulumi/pulumi/blob/3fad2e5329a5a851cd3913b54e26d2b2f64ba013/sdk/nodejs/automation/cmd.ts#L55
