### ISSUE TITLE
Intermittent (?) test failure in azure containers test.

### ISSUE THREAD

**Issue by ellismg** [pulumi/pulumi-cloud#680]
The nightly test run failed.  I looks like we failed to log into the azure container registry we deployed and things went off the rails from there:

```
[ loud/azure/examples/containers ] sample: /home/travis/gopath/src/github.com/pulumi/pulumi-cloud/azure/examples/containers
[ loud/azure/examples/containers ] pulumi: /home/travis/.pulumi/bin/pulumi
[ loud/azure/examples/containers ] **** Invoke '/usr/local/bin/yarn install --verbose' in '/tmp/p-it-travis-job-containers-0643c294-584946883'
[ loud/azure/examples/containers ] Still running command '/usr/local/bin/yarn install --verbose' (/tmp/p-it-travis-job-containers-0643c294-584946883)...
[ loud/azure/examples/containers ] Wrote output to /tmp/p-it-travis-job-containers-0643c294-584946883/command-output/yarn-install.20181221-200810.62fff.log
[ loud/azure/examples/containers ] **** Invoke '/usr/local/bin/yarn link @pulumi/cloud' in '/tmp/p-it-travis-job-containers-0643c294-584946883'
[ loud/azure/examples/containers ] Still running command '/usr/local/bin/yarn link @pulumi/cloud' (/tmp/p-it-travis-job-containers-0643c294-584946883)...
[ loud/azure/examples/containers ] Wrote output to /tmp/p-it-travis-job-containers-0643c294-584946883/command-output/yarn-link.20181221-200907.dbdc1.log
[ loud/azure/examples/containers ] **** Invoke '/usr/local/bin/yarn link @pulumi/cloud-azure' in '/tmp/p-it-travis-job-containers-0643c294-584946883'
[ loud/azure/examples/containers ] Wrote output to /tmp/p-it-travis-job-containers-0643c294-584946883/command-output/yarn-link.20181221-200924.359ea.log
[ loud/azure/examples/containers ] projdir: /tmp/p-it-travis-job-containers-0643c294-584946883
[ loud/azure/examples/containers ] Initializing project (dir /tmp/p-it-travis-job-containers-0643c294-584946883; stack p-it-travis-job-containers-0643c294)
[ loud/azure/examples/containers ] **** Invoke '/home/travis/.pulumi/bin/pulumi login --cloud-url https://api.pulumi.com --tracing https://tracing.pulumi-engineering.com/collector/api/v1/spans' in '/tmp/p-it-travis-job-containers-0643c294-584946883'
[ loud/azure/examples/containers ] Wrote output to /tmp/p-it-travis-job-containers-0643c294-584946883/command-output/pulumi-login.20181221-200926.c46b5.log
[ loud/azure/examples/containers ] **** Invoke '/home/travis/.pulumi/bin/pulumi stack init moolumi/p-it-travis-job-containers-0643c294 --tracing https://tracing.pulumi-engineering.com/collector/api/v1/spans' in '/tmp/p-it-travis-job-containers-0643c294-584946883'
[ loud/azure/examples/containers ] Wrote output to /tmp/p-it-travis-job-containers-0643c294-584946883/command-output/pulumi-stack-init.20181221-200927.9ac6f.log
[ loud/azure/examples/containers ] **** Invoke '/home/travis/.pulumi/bin/pulumi config set containers:redisPassword REDIS_PASSWORD --tracing https://tracing.pulumi-engineering.com/collector/api/v1/spans' in '/tmp/p-it-travis-job-containers-0643c294-584946883'
[ loud/azure/examples/containers ] **** Invoke '/home/travis/.pulumi/bin/pulumi config set azure:environment public --tracing https://tracing.pulumi-engineering.com/collector/api/v1/spans' in '/tmp/p-it-travis-job-containers-0643c294-584946883'
[ loud/azure/examples/containers ] **** Invoke '/home/travis/.pulumi/bin/pulumi config set cloud-azure:location West US 2 --tracing https://tracing.pulumi-engineering.com/collector/api/v1/spans' in '/tmp/p-it-travis-job-containers-0643c294-584946883'
[ loud/azure/examples/containers ] **** Invoke '/home/travis/.pulumi/bin/pulumi config set cloud-azure:subscriptionId 0282681f-7a9e-424b-80b2-96babd57a8a1 --tracing https://tracing.pulumi-engineering.com/collector/api/v1/spans' in '/tmp/p-it-travis-job-containers-0643c294-584946883'
[ loud/azure/examples/containers ] **** Invoke '/home/travis/.pulumi/bin/pulumi config set cloud-azure:clientId d5ffcf09-5f77-4525-a2f5-4c57d42e8445 --tracing https://tracing.pulumi-engineering.com/collector/api/v1/spans' in '/tmp/p-it-travis-job-containers-0643c294-584946883'
[ loud/azure/examples/containers ] **** Invoke '/home/travis/.pulumi/bin/pulumi config set cloud-azure:tenantId 25024bbc-53bb-4ccd-ab0c-26a4d95ccfd5 --tracing https://tracing.pulumi-engineering.com/collector/api/v1/spans' in '/tmp/p-it-travis-job-containers-0643c294-584946883'
[ loud/azure/examples/containers ] **** Invoke '/home/travis/.pulumi/bin/pulumi config set cloud:provider azure --tracing https://tracing.pulumi-engineering.com/collector/api/v1/spans' in '/tmp/p-it-travis-job-containers-0643c294-584946883'
[ loud/azure/examples/containers ] **** Invoke '/home/travis/.pulumi/bin/pulumi config set --secret cloud-azure:clientSecret [secure] --tracing https://tracing.pulumi-engineering.com/collector/api/v1/spans' in '/tmp/p-it-travis-job-containers-0643c294-584946883'
[ loud/azure/examples/containers ] Performing primary preview and update
[ loud/azure/examples/containers ] **** Invoke '/home/travis/.pulumi/bin/pulumi preview --non-interactive --tracing https://tracing.pulumi-engineering.com/collector/api/v1/spans' in '/tmp/p-it-travis-job-containers-0643c294-584946883'
[ loud/azure/examples/containers ] Still running command '/home/travis/.pulumi/bin/pulumi preview --non-interactive --tracing https://tracing.pulumi-engineering.com/collector/api/v1/spans' (/tmp/p-it-travis-job-containers-0643c294-584946883)...
[ loud/azure/examples/containers ] Wrote output to /tmp/p-it-travis-job-containers-0643c294-584946883/command-output/pulumi-preview-initial.20181221-201036.5a652.log
[ loud/azure/examples/containers ] **** Invoke '/home/travis/.pulumi/bin/pulumi up --non-interactive --skip-preview --tracing https://tracing.pulumi-engineering.com/collector/api/v1/spans' in '/tmp/p-it-travis-job-containers-0643c294-584946883'
[ loud/azure/examples/containers ] Still running command '/home/travis/.pulumi/bin/pulumi up --non-interactive --skip-preview --tracing https://tracing.pulumi-engineering.com/collector/api/v1/spans' (/tmp/p-it-travis-job-containers-0643c294-584946883)...
[ loud/azure/examples/containers ] Still running command '/home/travis/.pulumi/bin/pulumi up --non-interactive --skip-preview --tracing https://tracing.pulumi-engineering.com/collector/api/v1/spans' (/tmp/p-it-travis-job-containers-0643c294-584946883)...
[ loud/azure/examples/containers ] Still running command '/home/travis/.pulumi/bin/pulumi up --non-interactive --skip-preview --tracing https://tracing.pulumi-engineering.com/collector/api/v1/spans' (/tmp/p-it-travis-job-containers-0643c294-584946883)...
[ loud/azure/examples/containers ] Wrote output to /tmp/p-it-travis-job-containers-0643c294-584946883/command-output/pulumi-update-initial.20181221-201230.3db32.log
[ loud/azure/examples/containers ] Roundtripping checkpoint via stack export and stack import
[ loud/azure/examples/containers ] **** Invoke '/home/travis/.pulumi/bin/pulumi stack export --file stack.json --tracing https://tracing.pulumi-engineering.com/collector/api/v1/spans' in '/tmp/p-it-travis-job-containers-0643c294-584946883'
[ loud/azure/examples/containers ] **** Invoke '/home/travis/.pulumi/bin/pulumi stack import --file stack.json --tracing https://tracing.pulumi-engineering.com/collector/api/v1/spans' in '/tmp/p-it-travis-job-containers-0643c294-584946883'
[ loud/azure/examples/containers ] Wrote output to /tmp/p-it-travis-job-containers-0643c294-584946883/command-output/pulumi-stack-import.20181221-201233.03271.log
[ loud/azure/examples/containers ] Performing empty preview and update(no changes expected)
[ loud/azure/examples/containers ] **** Invoke '/home/travis/.pulumi/bin/pulumi preview --non-interactive --expect-no-changes --tracing https://tracing.pulumi-engineering.com/collector/api/v1/spans' in '/tmp/p-it-travis-job-containers-0643c294-584946883'
[ loud/azure/examples/containers ] Still running command '/home/travis/.pulumi/bin/pulumi preview --non-interactive --expect-no-changes --tracing https://tracing.pulumi-engineering.com/collector/api/v1/spans' (/tmp/p-it-travis-job-containers-0643c294-584946883)...
[ loud/azure/examples/containers ] Wrote output to /tmp/p-it-travis-job-containers-0643c294-584946883/command-output/pulumi-preview-empty.20181221-201314.77114.log
[ loud/azure/examples/containers ] **** Invoke '/home/travis/.pulumi/bin/pulumi up --non-interactive --skip-preview --expect-no-changes --tracing https://tracing.pulumi-engineering.com/collector/api/v1/spans' in '/tmp/p-it-travis-job-containers-0643c294-584946883'
[ loud/azure/examples/containers ] Still running command '/home/travis/.pulumi/bin/pulumi up --non-interactive --skip-preview --expect-no-changes --tracing https://tracing.pulumi-engineering.com/collector/api/v1/spans' (/tmp/p-it-travis-job-containers-0643c294-584946883)...
[ loud/azure/examples/containers ] Wrote output to /tmp/p-it-travis-job-containers-0643c294-584946883/command-output/pulumi-update-empty.20181221-201346.57ede.log
[ loud/azure/examples/containers ] **** Invoke '/home/travis/.pulumi/bin/pulumi refresh --non-interactive --skip-preview --tracing https://tracing.pulumi-engineering.com/collector/api/v1/spans' in '/tmp/p-it-travis-job-containers-0643c294-584946883'
[ loud/azure/examples/containers ] Still running command '/home/travis/.pulumi/bin/pulumi refresh --non-interactive --skip-preview --tracing https://tracing.pulumi-engineering.com/collector/api/v1/spans' (/tmp/p-it-travis-job-containers-0643c294-584946883)...
[ loud/azure/examples/containers ] Wrote output to /tmp/p-it-travis-job-containers-0643c294-584946883/command-output/pulumi-refresh.20181221-201436.54c8e.log
[ loud/azure/examples/containers ] Destroying stack
[ loud/azure/examples/containers ] **** Invoke '/home/travis/.pulumi/bin/pulumi destroy --non-interactive --skip-preview --tracing https://tracing.pulumi-engineering.com/collector/api/v1/spans' in '/tmp/p-it-travis-job-containers-0643c294-584946883'
[ loud/azure/examples/containers ] Still running command '/home/travis/.pulumi/bin/pulumi destroy --non-interactive --skip-preview --tracing https://tracing.pulumi-engineering.com/collector/api/v1/spans' (/tmp/p-it-travis-job-containers-0643c294-584946883)...
[ loud/azure/examples/containers ] Still running command '/home/travis/.pulumi/bin/pulumi destroy --non-interactive --skip-preview --tracing https://tracing.pulumi-engineering.com/collector/api/v1/spans' (/tmp/p-it-travis-job-containers-0643c294-584946883)...
[ loud/azure/examples/containers ] Wrote output to /tmp/p-it-travis-job-containers-0643c294-584946883/command-output/pulumi-destroy.20181221-201550.6cbc5.log
[ loud/azure/examples/containers ] **** Invoke '/home/travis/.pulumi/bin/pulumi stack rm --yes --tracing https://tracing.pulumi-engineering.com/collector/api/v1/spans' in '/tmp/p-it-travis-job-containers-0643c294-584946883'
[ loud/azure/examples/containers ] Wrote output to /tmp/p-it-travis-job-containers-0643c294-584946883/command-output/pulumi-stack-rm.20181221-201551.5c4d2.log
    --- PASS: Test_Examples//home/travis/gopath/src/github.com/pulumi/pulumi-cloud/azure/examples/containers (493.67s)
=== RUN   Test_Examples//home/travis/gopath/src/github.com/pulumi/pulumi-cloud/azure/examples/containers
=== PAUSE Test_Examples//home/travis/gopath/src/github.com/pulumi/pulumi-cloud/azure/examples/containers
=== CONT  Test_Examples//home/travis/gopath/src/github.com/pulumi/pulumi-cloud/azure/examples/containers
[ loud/azure/examples/containers ] sample: /home/travis/gopath/src/github.com/pulumi/pulumi-cloud/azure/examples/containers
[ loud/azure/examples/containers ] pulumi: /home/travis/.pulumi/bin/pulumi
[ loud/azure/examples/containers ] **** Invoke '/usr/local/bin/yarn install --verbose' in '/tmp/p-it-travis-job-containers-5cd6a4cb-377031351'
[ loud/azure/examples/containers ] Still running command '/usr/local/bin/yarn install --verbose' (/tmp/p-it-travis-job-containers-5cd6a4cb-377031351)...
[ loud/azure/examples/containers ] Still running command '/usr/local/bin/yarn install --verbose' (/tmp/p-it-travis-job-containers-5cd6a4cb-377031351)...
[ loud/azure/examples/containers ] Still running command '/usr/local/bin/yarn install --verbose' (/tmp/p-it-travis-job-containers-5cd6a4cb-377031351)...
[ loud/azure/examples/containers ] Wrote output to /tmp/p-it-travis-job-containers-5cd6a4cb-377031351/command-output/yarn-install.20181221-202507.f6bac.log
[ loud/azure/examples/containers ] **** Invoke '/usr/local/bin/yarn link @pulumi/cloud' in '/tmp/p-it-travis-job-containers-5cd6a4cb-377031351'
[ loud/azure/examples/containers ] Wrote output to /tmp/p-it-travis-job-containers-5cd6a4cb-377031351/command-output/yarn-link.20181221-202510.e985d.log
[ loud/azure/examples/containers ] **** Invoke '/usr/local/bin/yarn link @pulumi/cloud-azure' in '/tmp/p-it-travis-job-containers-5cd6a4cb-377031351'
[ loud/azure/examples/containers ] Wrote output to /tmp/p-it-travis-job-containers-5cd6a4cb-377031351/command-output/yarn-link.20181221-202513.34bce.log
[ loud/azure/examples/containers ] projdir: /tmp/p-it-travis-job-containers-5cd6a4cb-377031351
[ loud/azure/examples/containers ] Initializing project (dir /tmp/p-it-travis-job-containers-5cd6a4cb-377031351; stack p-it-travis-job-containers-5cd6a4cb)
[ loud/azure/examples/containers ] **** Invoke '/home/travis/.pulumi/bin/pulumi login --cloud-url https://api.pulumi.com --tracing https://tracing.pulumi-engineering.com/collector/api/v1/spans' in '/tmp/p-it-travis-job-containers-5cd6a4cb-377031351'
[ loud/azure/examples/containers ] Wrote output to /tmp/p-it-travis-job-containers-5cd6a4cb-377031351/command-output/pulumi-login.20181221-202515.a65fa.log
[ loud/azure/examples/containers ] **** Invoke '/home/travis/.pulumi/bin/pulumi stack init moolumi/p-it-travis-job-containers-5cd6a4cb --tracing https://tracing.pulumi-engineering.com/collector/api/v1/spans' in '/tmp/p-it-travis-job-containers-5cd6a4cb-377031351'
[ loud/azure/examples/containers ] Wrote output to /tmp/p-it-travis-job-containers-5cd6a4cb-377031351/command-output/pulumi-stack-init.20181221-202517.43afa.log
[ loud/azure/examples/containers ] **** Invoke '/home/travis/.pulumi/bin/pulumi config set cloud:provider azure --tracing https://tracing.pulumi-engineering.com/collector/api/v1/spans' in '/tmp/p-it-travis-job-containers-5cd6a4cb-377031351'
[ loud/azure/examples/containers ] **** Invoke '/home/travis/.pulumi/bin/pulumi config set containers:redisPassword REDIS_PASSWORD --tracing https://tracing.pulumi-engineering.com/collector/api/v1/spans' in '/tmp/p-it-travis-job-containers-5cd6a4cb-377031351'
[ loud/azure/examples/containers ] **** Invoke '/home/travis/.pulumi/bin/pulumi config set azure:environment public --tracing https://tracing.pulumi-engineering.com/collector/api/v1/spans' in '/tmp/p-it-travis-job-containers-5cd6a4cb-377031351'
[ loud/azure/examples/containers ] **** Invoke '/home/travis/.pulumi/bin/pulumi config set cloud-azure:location West US 2 --tracing https://tracing.pulumi-engineering.com/collector/api/v1/spans' in '/tmp/p-it-travis-job-containers-5cd6a4cb-377031351'
[ loud/azure/examples/containers ] **** Invoke '/home/travis/.pulumi/bin/pulumi config set cloud-azure:subscriptionId 0282681f-7a9e-424b-80b2-96babd57a8a1 --tracing https://tracing.pulumi-engineering.com/collector/api/v1/spans' in '/tmp/p-it-travis-job-containers-5cd6a4cb-377031351'
[ loud/azure/examples/containers ] **** Invoke '/home/travis/.pulumi/bin/pulumi config set cloud-azure:clientId d5ffcf09-5f77-4525-a2f5-4c57d42e8445 --tracing https://tracing.pulumi-engineering.com/collector/api/v1/spans' in '/tmp/p-it-travis-job-containers-5cd6a4cb-377031351'
[ loud/azure/examples/containers ] **** Invoke '/home/travis/.pulumi/bin/pulumi config set cloud-azure:tenantId 25024bbc-53bb-4ccd-ab0c-26a4d95ccfd5 --tracing https://tracing.pulumi-engineering.com/collector/api/v1/spans' in '/tmp/p-it-travis-job-containers-5cd6a4cb-377031351'
[ loud/azure/examples/containers ] **** Invoke '/home/travis/.pulumi/bin/pulumi config set --secret cloud-azure:clientSecret [secure] --tracing https://tracing.pulumi-engineering.com/collector/api/v1/spans' in '/tmp/p-it-travis-job-containers-5cd6a4cb-377031351'
[ loud/azure/examples/containers ] Performing primary preview and update
[ loud/azure/examples/containers ] **** Invoke '/home/travis/.pulumi/bin/pulumi preview --non-interactive --tracing https://tracing.pulumi-engineering.com/collector/api/v1/spans' in '/tmp/p-it-travis-job-containers-5cd6a4cb-377031351'
[ loud/azure/examples/containers ] Still running command '/home/travis/.pulumi/bin/pulumi preview --non-interactive --tracing https://tracing.pulumi-engineering.com/collector/api/v1/spans' (/tmp/p-it-travis-job-containers-5cd6a4cb-377031351)...
[ loud/azure/examples/containers ] Wrote output to /tmp/p-it-travis-job-containers-5cd6a4cb-377031351/command-output/pulumi-preview-initial.20181221-202628.1bea1.log
[ loud/azure/examples/containers ] **** Invoke '/home/travis/.pulumi/bin/pulumi up --non-interactive --skip-preview --tracing https://tracing.pulumi-engineering.com/collector/api/v1/spans' in '/tmp/p-it-travis-job-containers-5cd6a4cb-377031351'
[ loud/azure/examples/containers ] Still running command '/home/travis/.pulumi/bin/pulumi up --non-interactive --skip-preview --tracing https://tracing.pulumi-engineering.com/collector/api/v1/spans' (/tmp/p-it-travis-job-containers-5cd6a4cb-377031351)...
[ loud/azure/examples/containers ] Still running command '/home/travis/.pulumi/bin/pulumi up --non-interactive --skip-preview --tracing https://tracing.pulumi-engineering.com/collector/api/v1/spans' (/tmp/p-it-travis-job-containers-5cd6a4cb-377031351)...
[ loud/azure/examples/containers ] Still running command '/home/travis/.pulumi/bin/pulumi up --non-interactive --skip-preview --tracing https://tracing.pulumi-engineering.com/collector/api/v1/spans' (/tmp/p-it-travis-job-containers-5cd6a4cb-377031351)...
[ loud/azure/examples/containers ] Invoke '/home/travis/.pulumi/bin/pulumi up --non-interactive --skip-preview --tracing https://tracing.pulumi-engineering.com/collector/api/v1/spans' failed: exit status 255
[ loud/azure/examples/containers ] Updating (moolumi/p-it-travis-job-containers-5cd6a4cb):
[ loud/azure/examples/containers ] 
[ loud/azure/examples/containers ]  +  pulumi:pulumi:Stack containers-p-it-travis-job-containers-5cd6a4cb creating 
[ loud/azure/examples/containers ]  +  cloud:service:Service examples-cached-nginx creating 
[ loud/azure/examples/containers ]  +  cloud:global:infrastructure global-infrastructure creating 
[ loud/azure/examples/containers ]  +  cloud:service:Service examples-nginx creating 
[ loud/azure/examples/containers ] @ Updating....
[ loud/azure/examples/containers ]  +  pulumi:pulumi:Stack containers-p-it-travis-job-containers-5cd6a4cb creating flag provided but not defined: -tracing
[ loud/azure/examples/containers ]  +  pulumi:pulumi:Stack containers-p-it-travis-job-containers-5cd6a4cb creating Usage of tf-provider-flags:
[ loud/azure/examples/containers ]  +  pulumi:pulumi:Stack containers-p-it-travis-job-containers-5cd6a4cb creating   -get-provider-info
[ loud/azure/examples/containers ]  +  pulumi:pulumi:Stack containers-p-it-travis-job-containers-5cd6a4cb creating     	dump provider info as JSON to stdout
[ loud/azure/examples/containers ] @ Updating....
[ loud/azure/examples/containers ]  +  azure:core:ResourceGroup global creating 
[ loud/azure/examples/containers ]  +  azure:core:ResourceGroup global created 
[ loud/azure/examples/containers ]  +  azure:storage:Account global creating 
[ loud/azure/examples/containers ]  +  azure:containerservice:Group examples-nginx creating 
[ loud/azure/examples/containers ]  +  azure:containerservice:Registry global creating 
[ loud/azure/examples/containers ]  +  azure:appservice:Plan global-function-app creating 
[ loud/azure/examples/containers ] @ Updating....
[ loud/azure/examples/containers ]  +  azure:containerservice:Group examples-nginx created 
[ loud/azure/examples/containers ]  +  azure:appservice:Plan global-function-app created 
[ loud/azure/examples/containers ]  +  azure:containerservice:Registry global created 
[ loud/azure/examples/containers ]  +  pulumi:pulumi:Stack containers-p-it-travis-job-containers-5cd6a4cb created     	dump provider info as JSON to stdout
[ loud/azure/examples/containers ]  +  azure:storage:Account global created 
[ loud/azure/examples/containers ]  +  pulumi:pulumi:Stack containers-p-it-travis-job-containers-5cd6a4cb created     	dump provider info as JSON to stdout
[ loud/azure/examples/containers ]  +  pulumi:pulumi:Stack containers-p-it-travis-job-containers-5cd6a4cb created     	dump provider info as JSON to stdout
[ loud/azure/examples/containers ]  +  azure:storage:Container global creating 
[ loud/azure/examples/containers ]  +  pulumi:pulumi:Stack containers-p-it-travis-job-containers-5cd6a4cb created     	dump provider info as JSON to stdout
[ loud/azure/examples/containers ]  +  pulumi:pulumi:Stack containers-p-it-travis-job-containers-5cd6a4cb created     	dump provider info as JSON to stdout
[ loud/azure/examples/containers ]  +  pulumi:pulumi:Stack containers-p-it-travis-job-containers-5cd6a4cb created     	dump provider info as JSON to stdout
[ loud/azure/examples/containers ]  +  pulumi:pulumi:Stack containers-p-it-travis-job-containers-5cd6a4cb created     	dump provider info as JSON to stdout
[ loud/azure/examples/containers ]  +  pulumi:pulumi:Stack containers-p-it-travis-job-containers-5cd6a4cb created     	dump provider info as JSON to stdout
[ loud/azure/examples/containers ]  +  pulumi:pulumi:Stack containers-p-it-travis-job-containers-5cd6a4cb created     	dump provider info as JSON to stdout
[ loud/azure/examples/containers ]  +  pulumi:pulumi:Stack containers-p-it-travis-job-containers-5cd6a4cb created warning: Error response from daemon: manifest for globald32640e6.azurecr.io/p-it-travis-job-containers-5cd6a4cb-container-164fa748:latest not found
[ loud/azure/examples/containers ]  +  pulumi:pulumi:Stack containers-p-it-travis-job-containers-5cd6a4cb created warning: Error response from daemon: manifest for globald32640e6.azurecr.io/p-it-travis-job-containers-5cd6a4cb-container-164fa748:latest not found
[ loud/azure/examples/containers ]  +  pulumi:pulumi:Stack containers-p-it-travis-job-containers-5cd6a4cb created warning: Error response from daemon: manifest for globald32640e6.azurecr.io/p-it-travis-job-containers-5cd6a4cb-container-164fa748:latest not found
[ loud/azure/examples/containers ]  +  pulumi:pulumi:Stack containers-p-it-travis-job-containers-5cd6a4cb created warning: Error response from daemon: manifest for globald32640e6.azurecr.io/p-it-travis-job-containers-5cd6a4cb-container-164fa748:latest not found
[ loud/azure/examples/containers ]  +  pulumi:pulumi:Stack containers-p-it-travis-job-containers-5cd6a4cb created warning: Error response from daemon: manifest for globald32640e6.azurecr.io/p-it-travis-job-containers-5cd6a4cb-container-164fa748:latest not found
[ loud/azure/examples/containers ]  +  pulumi:pulumi:Stack containers-p-it-travis-job-containers-5cd6a4cb created warning: Error response from daemon: manifest for globald32640e6.azurecr.io/p-it-travis-job-containers-5cd6a4cb-container-164fa748:latest not found
[ loud/azure/examples/containers ]  +  pulumi:pulumi:Stack containers-p-it-travis-job-containers-5cd6a4cb created warning: Error response from daemon: manifest for globald32640e6.azurecr.io/p-it-travis-job-containers-5cd6a4cb-container-164fa748:latest not found
[ loud/azure/examples/containers ]  +  pulumi:pulumi:Stack containers-p-it-travis-job-containers-5cd6a4cb created warning: Error response from daemon: manifest for globald32640e6.azurecr.io/p-it-travis-job-containers-5cd6a4cb-container-164fa748:latest not found
[ loud/azure/examples/containers ]  +  pulumi:pulumi:Stack containers-p-it-travis-job-containers-5cd6a4cb created warning: Error response from daemon: manifest for globald32640e6.azurecr.io/p-it-travis-job-containers-5cd6a4cb-container-164fa748:latest not found
[ loud/azure/examples/containers ]  +  pulumi:pulumi:Stack containers-p-it-travis-job-containers-5cd6a4cb created warning: Error response from daemon: manifest for globald32640e6.azurecr.io/p-it-travis-job-containers-5cd6a4cb-container-164fa748:latest not found
[ loud/azure/examples/containers ]  +  pulumi:pulumi:Stack containers-p-it-travis-job-containers-5cd6a4cb created warning: Error response from daemon: manifest for globald32640e6.azurecr.io/p-it-travis-job-containers-5cd6a4cb-container-164fa748:latest not found
[ loud/azure/examples/containers ]  +  pulumi:pulumi:Stack containers-p-it-travis-job-containers-5cd6a4cb created warning: Error response from daemon: manifest for globald32640e6.azurecr.io/p-it-travis-job-containers-5cd6a4cb-container-164fa748:latest not found
[ loud/azure/examples/containers ]  +  pulumi:pulumi:Stack containers-p-it-travis-job-containers-5cd6a4cb created warning: Error response from daemon: manifest for globald32640e6.azurecr.io/p-it-travis-job-containers-5cd6a4cb-container-164fa748:latest not found
[ loud/azure/examples/containers ]  +  pulumi:pulumi:Stack containers-p-it-travis-job-containers-5cd6a4cb created warning: Error response from daemon: manifest for globald32640e6.azurecr.io/p-it-travis-job-containers-5cd6a4cb-container-164fa748:latest not found
[ loud/azure/examples/containers ]  +  pulumi:pulumi:Stack containers-p-it-travis-job-containers-5cd6a4cb created warning: Error response from daemon: manifest for globald32640e6.azurecr.io/p-it-travis-job-containers-5cd6a4cb-container-164fa748:latest not found
[ loud/azure/examples/containers ]  +  azure:storage:Container global created 
[ loud/azure/examples/containers ] @ Updating....
[ loud/azure/examples/containers ]  +  pulumi:pulumi:Stack containers-p-it-travis-job-containers-5cd6a4cb **creating failed** error: unauthorized: authentication required
[ loud/azure/examples/containers ]  +  pulumi:pulumi:Stack containers-p-it-travis-job-containers-5cd6a4cb **creating failed** error: Error: 'docker push globald32640e6.azurecr.io/p-it-travis-job-containers-5cd6a4cb-container-164fa748:dbfa24b5ad95090ca94b30cb64be4b44e0c70f015e2505901a1f5d9c123d9cf6' failed with exit code 1
[ loud/azure/examples/containers ]  +  pulumi:pulumi:Stack containers-p-it-travis-job-containers-5cd6a4cb **creating failed** error: Error: 'docker push globald32640e6.azurecr.io/p-it-travis-job-containers-5cd6a4cb-container-164fa748:dbfa24b5ad95090ca94b30cb64be4b44e0c70f015e2505901a1f5d9c123d9cf6' failed with exit code 1
[ loud/azure/examples/containers ]  +  pulumi:pulumi:Stack containers-p-it-travis-job-containers-5cd6a4cb **creating failed** error: an unhandled error occurred: Program exited with non-zero exit code: 1
[ loud/azure/examples/containers ]  +  cloud:service:Service examples-cached-nginx created 
[ loud/azure/examples/containers ]  +  cloud:global:infrastructure global-infrastructure created 
[ loud/azure/examples/containers ]  +  cloud:service:Service examples-nginx created 
[ loud/azure/examples/containers ]  
[ loud/azure/examples/containers ] Diagnostics:
[ loud/azure/examples/containers ]   pulumi:pulumi:Stack (containers-p-it-travis-job-containers-5cd6a4cb):
[ loud/azure/examples/containers ]     flag provided but not defined: -tracing
[ loud/azure/examples/containers ]     Usage of tf-provider-flags:
[ loud/azure/examples/containers ]       -get-provider-info
[ loud/azure/examples/containers ]         	dump provider info as JSON to stdout
[ loud/azure/examples/containers ]  
[ loud/azure/examples/containers ]     error: Error: 'docker push globald32640e6.azurecr.io/p-it-travis-job-containers-5cd6a4cb-container-164fa748:dbfa24b5ad95090ca94b30cb64be4b44e0c70f015e2505901a1f5d9c123d9cf6' failed with exit code 1
[ loud/azure/examples/containers ]     The push refers to a repository [globald32640e6.azurecr.io/p-it-travis-job-containers-5cd6a4cb-container-164fa748]
[ loud/azure/examples/containers ]     a380e873d470: Preparing
[ loud/azure/examples/containers ]     ece4f9fdef59: Preparing
[ loud/azure/examples/containers ]     ad5345cbb119: Preparing
[ loud/azure/examples/containers ]     ef68f6734aa4: Preparing
[ loud/azure/examples/containers ]     ece4f9fdef59: Waiting
[ loud/azure/examples/containers ]     ad5345cbb119: Waiting
[ loud/azure/examples/containers ]     ef68f6734aa4: Waiting
[ loud/azure/examples/containers ]     a380e873d470: Waiting
[ loud/azure/examples/containers ]     
[ loud/azure/examples/containers ]         at /opt/pulumi/node_modules/@pulumi/cloud-azure/node_modules/@pulumi/docker.ts:513:15
[ loud/azure/examples/containers ]         at Generator.next (<anonymous>)
[ loud/azure/examples/containers ]         at fulfilled (/opt/pulumi/node_modules/@pulumi/cloud-azure/node_modules/@pulumi/docker/docker.js:17:58)
[ loud/azure/examples/containers ]         at <anonymous>
[ loud/azure/examples/containers ]         at process._tickCallback (internal/process/next_tick.js:188:7)
[ loud/azure/examples/containers ]     error: an unhandled error occurred: Program exited with non-zero exit code: 1
[ loud/azure/examples/containers ]  
[ loud/azure/examples/containers ]     warning: Error response from daemon: manifest for globald32640e6.azurecr.io/p-it-travis-job-containers-5cd6a4cb-container-164fa748:latest not found
[ loud/azure/examples/containers ]  
[ loud/azure/examples/containers ]     error: unauthorized: authentication required
[ loud/azure/examples/containers ]  
[ loud/azure/examples/containers ] Outputs:
[ loud/azure/examples/containers ]     nginxEndpoint: {
[ loud/azure/examples/containers ]         hostname: "40.91.114.102"
[ loud/azure/examples/containers ]         port    : 80
[ loud/azure/examples/containers ]     }
[ loud/azure/examples/containers ] 
[ loud/azure/examples/containers ] Resources:
[ loud/azure/examples/containers ]     + 10 created
[ loud/azure/examples/containers ] 
[ loud/azure/examples/containers ] Duration: 1m25s
[ loud/azure/examples/containers ] 
[ loud/azure/examples/containers ] Permalink: https://app.pulumi.com/moolumi/p-it-travis-job-containers-5cd6a4cb/updates/1
[ loud/azure/examples/containers ] error: update failed
[ loud/azure/examples/containers ] 
[ loud/azure/examples/containers ] Wrote output to /tmp/p-it-travis-job-containers-5cd6a4cb-377031351/command-output/pulumi-update-initial.20181221-202758.5e30a.log
[ loud/azure/examples/containers ] Destroying stack
[ loud/azure/examples/containers ] **** Invoke '/home/travis/.pulumi/bin/pulumi destroy --non-interactive --skip-preview --tracing https://tracing.pulumi-engineering.com/collector/api/v1/spans' in '/tmp/p-it-travis-job-containers-5cd6a4cb-377031351'
[ loud/azure/examples/containers ] Still running command '/home/travis/.pulumi/bin/pulumi destroy --non-interactive --skip-preview --tracing https://tracing.pulumi-engineering.com/collector/api/v1/spans' (/tmp/p-it-travis-job-containers-5cd6a4cb-377031351)...
[ loud/azure/examples/containers ] Still running command '/home/travis/.pulumi/bin/pulumi destroy --non-interactive --skip-preview --tracing https://tracing.pulumi-engineering.com/collector/api/v1/spans' (/tmp/p-it-travis-job-containers-5cd6a4cb-377031351)...
[ loud/azure/examples/containers ] Wrote output to /tmp/p-it-travis-job-containers-5cd6a4cb-377031351/command-output/pulumi-destroy.20181221-202909.2a349.log
[ loud/azure/examples/containers ] **** Invoke '/home/travis/.pulumi/bin/pulumi stack rm --yes --tracing https://tracing.pulumi-engineering.com/collector/api/v1/spans' in '/tmp/p-it-travis-job-containers-5cd6a4cb-377031351'
[ loud/azure/examples/containers ] Wrote output to /tmp/p-it-travis-job-containers-5cd6a4cb-377031351/command-output/pulumi-stack-rm.20181221-202909.48c7d.log
```

The full job is here: https://travis-ci.com/pulumi/pulumi-cloud/builds/95574812

**Comment by lukehoban** [comment]
Duping against https://github.com/pulumi/pulumi-cloud/issues/682 which is tracking a few other failures.
