### ISSUE TITLE
Nightly tests are failing (several issues)

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-cloud#682]
This repo's nightly tests have been failing for over ~~a~~ two week(s).

* ~~[3154](https://travis-ci.com/pulumi/pulumi-cloud/builds/95937850): `pulumi-cloud/aws/tests/unit`~~
* [3153](https://travis-ci.com/pulumi/pulumi-cloud/builds/95904606): `pulumi-cloud/azure/examples/containers`
* ~~[3152](https://travis-ci.com/pulumi/pulumi-cloud/builds/95836336): `pulumi-cloud/aws/tests/unit`~~
* [3151](https://travis-ci.com/pulumi/pulumi-cloud/builds/95766859): `pulumi-cloud/azure/examples/cloud-ts-thumbnailer`
* ~~[3150](https://travis-ci.com/pulumi/pulumi-cloud/builds/95718195): `pulumi-cloud/aws/tests/unit`~~
* [3149](https://travis-ci.com/pulumi/pulumi-cloud/builds/95686526): `pulumi-cloud/examples/timers`
* [3148](https://travis-ci.com/pulumi/pulumi-cloud/builds/95641237): `pulumi-cloud/azure/examples/cloud-ts-thumbnailer`
* [3147](https://travis-ci.com/pulumi/pulumi-cloud/builds/95614934): `pulumi-cloud/azure/examples/containers`
* [3146](https://travis-ci.com/pulumi/pulumi-cloud/builds/95574812): `pulumi-cloud/azure/examples/containers`
* [3145](https://travis-ci.com/pulumi/pulumi-cloud/builds/95455001): `pulumi-cloud/examples/todo`

### `pulumi-cloud/azure/examples/cloud-ts-thumbnailer` 

```
    --- FAIL: Test_Examples//home/travis/gopath/src/github.com/pulumi/pulumi-cloud/azure/examples/cloud-ts-thumbnailer (506.25s)
[ /examples/cloud-ts-thumbnailer ]   cloud:task:Task (ffmpegThumbTask):
[ /examples/cloud-ts-thumbnailer ]     error: Error: 'docker push globalbe279b82.azurecr.io/p-it-travis-job-cloud-ts-t-42d0a377-container-dc8d99de:512a7aa61c18fa939870d4f35ceda87ffe4b5bb33b2e71fd80e97580daa0eea3' failed with exit code 1
[ /examples/cloud-ts-thumbnailer ]     The push refers to a repository [globalbe279b82.azurecr.io/p-it-travis-job-cloud-ts-t-42d0a377-container-dc8d99de]
[ /examples/cloud-ts-thumbnailer ]     
[ /examples/cloud-ts-thumbnailer ]         at /opt/pulumi/node_modules/@pulumi/cloud-azure/node_modules/@pulumi/docker.ts:513:15
[ /examples/cloud-ts-thumbnailer ]         at Generator.next (<anonymous>)
[ /examples/cloud-ts-thumbnailer ]         at fulfilled (/opt/pulumi/node_modules/@pulumi/cloud-azure/node_modules/@pulumi/docker/docker.js:17:58)
[ /examples/cloud-ts-thumbnailer ]         at <anonymous>
[ /examples/cloud-ts-thumbnailer ]         at process._tickDomainCallback (internal/process/next_tick.js:228:7)
[ /examples/cloud-ts-thumbnailer ]  
[ /examples/cloud-ts-thumbnailer ]     error: Get https://globalbe279b82.azurecr.io/v2/: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

### `pulumi-cloud/aws/tests/unit`

```
FAIL: Test_Examples//home/travis/gopath/src/github.com/pulumi/pulumi-cloud/aws/tests/unit (1327.23s)
        examples_harness.go:186: Expected to get status code 200 for https://s3u83mzp2j.execute-api.us-east-1.amazonaws.com/stage//unittests. Got: 504
        examples_harness.go:186: Expected to get status code 200 for https://s3u83mzp2j.execute-api.us-east-1.amazonaws.com/stage//unittests. Got: 500
        examples_harness.go:186: Expected to get status code 200 for https://s3u83mzp2j.execute-api.us-east-1.amazonaws.com/stage//unittests. Got: 500
        examples_harness.go:186: Expected to get status code 200 for https://s3u83mzp2j.execute-api.us-east-1.amazonaws.com/stage//unittests. Got: 500
	Error Trace:	examples_harness.go:193
			aws_test.go:284
			aws_test.go:191
			program.go:1010
			program.go:759
			program.go:642
			program.go:436
			aws_test.go:227
	Error:		Not equal: 200 (expected)
            	        != 500 (actual)
	Messages:	Got unexpected status code
```

### `pulumi-cloud/examples/timers`

```
[ i/pulumi-cloud/examples/timers ]   aws:lambda:Function (examples-test-daily):
[ i/pulumi-cloud/examples/timers ]     error: Plan apply failed: Error creating Lambda function: SerializationError: failed decoding REST JSON error response
[ i/pulumi-cloud/examples/timers ]     	status code: 400, request id:
[ i/pulumi-cloud/examples/timers ]     caused by: invalid character '<' looking for beginning of value
[ i/pulumi-cloud/examples/timers ]  
[ i/pulumi-cloud/examples/timers ] Resources:
[ i/pulumi-cloud/examples/timers ]     + 88 created
[ i/pulumi-cloud/examples/timers ] 
[ i/pulumi-cloud/examples/timers ] Duration: 1m38s
[ i/pulumi-cloud/examples/timers ] 
[ i/pulumi-cloud/examples/timers ] Permalink: https://app.pulumi.com/moolumi/p-it-travis-job-timers-ea4775c5/updates/1
[ i/pulumi-cloud/examples/timers ] error: update failed
```

### `pulumi-cloud/azure/examples/containers`

```
[ loud/azure/examples/containers ] Diagnostics:
[ loud/azure/examples/containers ]   pulumi:pulumi:Stack (containers-p-it-travis-job-containers-2199e846):
[ loud/azure/examples/containers ]     flag provided but not defined: -tracing
[ loud/azure/examples/containers ]     Usage of tf-provider-flags:
[ loud/azure/examples/containers ]       -get-provider-info
[ loud/azure/examples/containers ]         	dump provider info as JSON to stdout
[ loud/azure/examples/containers ]  
[ loud/azure/examples/containers ]     error: Error: 'docker push global2ed27ca1.azurecr.io/p-it-travis-job-containers-2199e846-container-164fa748:181d406dd81a01fb5da4d3db08940ac8c2f4e1cc90877cde510c96edbdae9231' failed with exit code 1
[ loud/azure/examples/containers ]     The push refers to a repository [global2ed27ca1.azurecr.io/p-it-travis-job-containers-2199e846-container-164fa748]
[ loud/azure/examples/containers ]     5820a262db31: Preparing
[ loud/azure/examples/containers ]     ece4f9fdef59: Preparing
[ loud/azure/examples/containers ]     ad5345cbb119: Preparing
[ loud/azure/examples/containers ]     ef68f6734aa4: Preparing
[ loud/azure/examples/containers ]     5820a262db31: Waiting
[ loud/azure/examples/containers ]     ece4f9fdef59: Waiting
[ loud/azure/examples/containers ]     ad5345cbb119: Waiting
[ loud/azure/examples/containers ]     ef68f6734aa4: Waiting
[ loud/azure/examples/containers ]     
[ loud/azure/examples/containers ]         at /opt/pulumi/node_modules/@pulumi/cloud-azure/node_modules/@pulumi/docker.ts:513:15
[ loud/azure/examples/containers ]         at Generator.next (<anonymous>)
[ loud/azure/examples/containers ]         at fulfilled (/opt/pulumi/node_modules/@pulumi/cloud-azure/node_modules/@pulumi/docker/docker.js:17:58)
[ loud/azure/examples/containers ]         at <anonymous>
[ loud/azure/examples/containers ]         at process._tickCallback (internal/process/next_tick.js:188:7)
[ loud/azure/examples/containers ]     error: an unhandled error occurred: Program exited with non-zero exit code: 1
[ loud/azure/examples/containers ]  
[ loud/azure/examples/containers ]     warning: Error response from daemon: manifest for global2ed27ca1.azurecr.io/p-it-travis-job-containers-2199e846-container-164fa748:latest not found
[ loud/azure/examples/containers ]  
[ loud/azure/examples/containers ]     error: unauthorized: authentication required
[ loud/azure/examples/containers ]  
[ loud/azure/examples/containers ] Outputs:
[ loud/azure/examples/containers ]     nginxEndpoint: {
[ loud/azure/examples/containers ]         hostname: "40.91.114.176"
[ loud/azure/examples/containers ]         port    : 80
[ loud/azure/examples/containers ]     }
[ loud/azure/examples/containers ] 
[ loud/azure/examples/containers ] Resources:
[ loud/azure/examples/containers ]     + 10 created
[ loud/azure/examples/containers ] 
[ loud/azure/examples/containers ] Duration: 1m27s
[ loud/azure/examples/containers ] 
[ loud/azure/examples/containers ] Permalink: https://app.pulumi.com/moolumi/p-it-travis-job-containers-2199e846/updates/1
[ loud/azure/examples/containers ] error: update failed
```

### `pulumi-cloud/examples/todo`

```
[ umi/pulumi-cloud/examples/todo ] Diagnostics:
[ umi/pulumi-cloud/examples/todo ]   aws:dynamodb:Table (examples-todo):
[ umi/pulumi-cloud/examples/todo ]     error: Plan apply failed: deleting urn:pulumi:p-it-travis-job-todo-b96ac644::todo::cloud:table:Table$aws:dynamodb/table:Table::examples-todo: timeout while waiting for resource to be gone (last state: 'DELETING', timeout: 10m0s)
[ umi/pulumi-cloud/examples/todo ]  
[ umi/pulumi-cloud/examples/todo ]   pulumi:pulumi:Stack (todo-p-it-travis-job-todo-b96ac644):
[ umi/pulumi-cloud/examples/todo ]     flag provided but not defined: -tracing
[ umi/pulumi-cloud/examples/todo ]     Usage of tf-provider-flags:
[ umi/pulumi-cloud/examples/todo ]       -get-provider-info
[ umi/pulumi-cloud/examples/todo ]         	dump provider info as JSON to stdout
[ umi/pulumi-cloud/examples/todo ]  
[ umi/pulumi-cloud/examples/todo ] Resources:
[ umi/pulumi-cloud/examples/todo ]     - 11 deleted
[ umi/pulumi-cloud/examples/todo ] 
[ umi/pulumi-cloud/examples/todo ] Duration: 10m9s
[ umi/pulumi-cloud/examples/todo ] 
[ umi/pulumi-cloud/examples/todo ] Permalink: https://app.pulumi.com/moolumi/p-it-travis-job-todo-b96ac644/updates/5
[ umi/pulumi-cloud/examples/todo ] error: update failed
```

and 

```
examples_harness.go:122: GET https://siw2zuu7t6.execute-api.us-east-2.amazonaws.com/stage//favicon.ico [200/image/x-icon]: ...
        examples_harness.go:129: POST https://siw2zuu7t6.execute-api.us-east-2.amazonaws.com/stage//todo/abc [201]: ...
        examples_harness.go:137: GET https://siw2zuu7t6.execute-api.us-east-2.amazonaws.com/stage//todo/abc [401]: Authorization header required
        examples_harness.go:144: GET https://siw2zuu7t6.execute-api.us-east-2.amazonaws.com/stage//todo [200]: [{"id":"abc","value":"xyz"}]
	Error Trace:	program.go:638
			program.go:647
			program.go:436
			examples_harness.go:167
	Error:		Received unexpected error exit status 255
```

**Comment by CyrusNajmabadi** [comment]
Looking at this now.

**Comment by CyrusNajmabadi** [comment]
Have addressed pulumi-cloud/aws/tests/unit.   Looking for more info as to the source of the ohter failures.

**Comment by CyrusNajmabadi** [comment]
Moving out as we've had 6 good nightly runs in a row.  A major problem does still seem to be azure flakeyness.  But we need to have a strategy on what to do about that as that's not something in our control, and things are dying in the terraform layer.  As we see things, we may have to consider upstreaming fixes into terraform to do appropriate retries and whatnot in places they are missing them.

**Comment by joeduffy** [comment]
@CyrusNajmabadi Great to see this behind us! Given that we believe this is fixed, let's close out this catch-all bug, and reopen with more specific details should subsequent failures occur.
